package com.bocktrow.lom.statistic;

public enum Statistic {
    ABILITY_POWER, ATTACK_DAMAGE, CRITICAL_DAMAGE,
    LIFE_STEAL,
    HEALTH, MANA,
    ARMOR, MAGIC_RESISTANCE,
    COOLDOWN_REDUCTION, MOVEMENT_SPEED,
    HEALTH_REGEN, MANA_REGEN
}
